version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: fluffy-mongodb
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
      - ./fluffy-server/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      - MONGO_INITDB_DATABASE=fluffy_store
    networks:
      - fluffy-network

networks:
  fluffy-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local